#!/bin/bash

# Execute script with: $ sh setup_edgemesh_cloudside.sh --cloudside-ip=<the IP of the Cloudcore> --relay-node-name=<The Cloudside Node name (e.g. kube-cloudcore)>

CLOUDSIDE_IP=""
RELAY_NODE_NAME=""

# Parse args
while [ $# -gt 0 ]; do
  case "$1" in
    --cloudside-ip=*)
      CLOUDSIDE_IP="${1#*=}"
      ;;
    --relay-node-name=*)
      RELAY_NODE_NAME="${1#*=}"
      ;;
    *)
      echo "Error: Invalid argument: $1"
      exit 1
      ;;
  esac
  shift
done

# NOTE: With the keadm init command in bootstrap_cloudside.sh, the basic adjustment for EdgeMesh for Cloudside is made
# REF: https://edgemesh.netlify.app/guide/edge-kube-api.html#quick-start

sudo su

# Generate PSK-Cypher and save it in .txt
# REF: https://edgemesh.netlify.app/guide/security.html#generate-psk-cipher
openssl rand -base64 32 >> psk_cypher.txt
PSK=$(cat psk_cypher.txt)

# Install EdgeMesh via HELM
helm install edgemesh --namespace kubeedge \
--set agent.psk=$PSK \
--set agent.relayNodes[0].nodeName=$RELAY_NODE_NAME,agent.relayNodes[0].advertiseAddress="{$CLOUDSIDE_IP}" \
https://raw.githubusercontent.com/kubeedge/edgemesh/main/build/helm/edgemesh.tgz


# Install EdgeMesh-Gateway
# NOTE: The standard HELM-File seems to be broken for the Gateway component so it has be installed manually
# REF: https://edgemesh.netlify.app/guide/edge-gateway.html#deploy

kubectl apply -f manifests/01-serviceaccount.yaml
kubectl apply -f manifests/02-clusterrole.yaml
kubectl apply -f manifests/03-clusterrolebinding.yaml
# TODO: Refactor with HELM
echo "
apiVersion: v1
kind: ConfigMap
metadata:
  name: edgemesh-gateway-cfg
  namespace: kubeedge
  labels:
    k8s-app: kubeedge
    kubeedge: edgemesh-gateway
data:
  edgemesh-gateway.yaml: |
    # For more detailed configuration, please refer to: https://edgemesh.netlify.app/reference/config-items.html#edgemesh-gateway-cfg
    modules:
      edgeGateway:
        enable: true
      edgeTunnel:
        enable: true
        relayNodes:
        - nodeName: $RELAY_NODE_NAME
          advertiseAddress:
          - $CLOUDSIDE_IP
        #- nodeName: <your relay node name2>
        #  advertiseAddress:
        #  - 2.2.2.2
        #  - 3.3.3.3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: edgemesh-gateway-psk
  namespace: kubeedge
  labels:
    k8s-app: kubeedge
    kubeedge: edgemesh-gateway
data:
  # Generated by `openssl rand -base64 32`
  # NOTE: Don't use this psk, please regenerate it!!! Please refer to: https://edgemesh.netlify.app/guide/security.html
  psk: $PSK
" | kubectl apply -f -
echo "
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgemesh-gateway
  namespace: kubeedge
  labels:
    k8s-app: kubeedge
    kubeedge: edgemesh-gateway
spec:
  selector:
    matchLabels:
      k8s-app: kubeedge
      kubeedge: edgemesh-gateway
  template:
    metadata:
      labels:
        k8s-app: kubeedge
        kubeedge: edgemesh-gateway
    spec:
      nodeName: $RELAY_NODE_NAME
      hostNetwork: true
      containers:
        - name: edgemesh-gateway
          securityContext:
            privileged: true
          image: kubeedge/edgemesh-gateway:v1.13.2
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: conf
              mountPath: /etc/edgemesh/config
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
            - name: psk
              mountPath: /etc/edgemesh
      restartPolicy: Always
      serviceAccountName: edgemesh-gateway
      volumes:
        - name: conf
          configMap:
            name: edgemesh-gateway-cfg
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: psk
          configMap:
            name: edgemesh-gateway-psk
" | kubectl apply -f -


# # Create HTTP-Gateway
# # REF: https://edgemesh.netlify.app/guide/edge-gateway.html#http-gateway
# kubectl apply -f examples/hostname-lb-random-gateway.yaml
