apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      nodeSelector:
        node-role.kubernetes.io/edge: "" # Selects nodes with the label "node-role.kubernetes.io/edge"
        edgenode: edgenode_X # Selects nodes with the label "edgenode: edgenode_001", CHANGE X!
      containers:
      - name: grafana
        image: grafana/grafana
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
