apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-edgenode00X # CHANGE X!
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
        edgenode: edgenode_00X # CHANGE X!
    spec:
      nodeSelector:
        node-role.kubernetes.io/edge: ""
        edgenode: edgenode_00X # CHANGE X!
      containers:
      - name: grafana
        image: grafana/grafana
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
