apiVersion: v1
kind: Namespace
metadata:
  name: sample-physical-model
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-physical-model-deployment
  namespace: sample-physical-model
spec:
  selector:
    matchLabels:
      app: sample-physical-model
      role: edge
      edgenode: edgenode_00X # CHANGE X!
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-physical-model
        role: edge
        edgenode: edgenode_00X # CHANGE X!
    spec:
      hostNetwork: false # NOTE!
      nodeSelector:
        kubernetes.io/hostname: kube-edgecore1-dev-l # Set the node selector to specify the node
      containers:
      - name: sample-physical-model
        image: docker.io/dangelic/edgecluster-prototype-dockerhub-registry:phymodel_alpha_v0-0-1
        ports:
        - containerPort: 1883
        env:
        - name: BROKER_URL
          value: "mqtt://10.43.75.28:1883" # Set the value of BROKER_URL to the Broker URL
        - name: DOWNSTREAM_TOPIC
          value: "test/down" # This is the topic the model subscribes to
        - name: UPSTREAM_TOPIC
          value: "test/up" # This is the topic the model publishes result data on
