apiVersion: v1
kind: Namespace
metadata:
  name: sample-physical-model
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-physical-model-deployment
  namespace: sample-physical-model
spec:
  selector:
    matchLabels:
      app: sample-physical-model
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-physical-model
    spec:
      hostNetwork: true # NOTE!
      nodeSelector:
        kubernetes.io/hostname: <NAME OF EDGE NODE> # Set the node selector to specify the node
      containers:
      - name: sample-physical-model
        image: docker.io/dangelic/edgecluster-prototype-dockerhub-registry:phymodel_v0-0-1
        ports:
        - containerPort: 1883
        env:
        - name: BROKER_URL
          value: "<mqtt://localhost:8080 or specific>" # Set the value of BROKER_URL to the Broker URL
        - name: DOWNSTREAM_TOPIC
          value: "<DOWNSTREAM TOPIC>" # This is the topic the model subscribes to
        - name: UPSTREAM_TOPIC
          value: "<UPSTREAM TOPIC" # This is the topic the model publishes result data on
